name: betsquad
description: A social betting application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.4
  firebase_auth: ^0.15.4
  firebase_storage: ^3.1.3
  modal_progress_hud: ^0.1.3
  image_picker: ^0.6.3+4
  http: ^0.12.0+4
  flutter_datetime_picker: ^1.3.4
  intl: ^0.16.1
  material_design_icons_flutter: 3.4.4995
  calendar_strip: ^1.0.6
  sqflite: ^1.2.2+1
  path_provider: ^1.6.5
  provider: ^4.0.4
  currency_textfield: ^1.0.3
  firebase_database: ^3.1.6
  custom_navigator: ^0.3.0
  rich_alert: ^0.1.32
  google_fonts: ^1.1.0

dev_dependencies:
  flutter_test:
   sdk: flutter


flutter:
  uses-material-design: true

  fonts:
  - family: CustomIcons
    fonts:
      - asset: lib/fonts/CustomIcons.ttf

  assets:
    - images/

