name: betsquad
description: A social betting application.

version: 1.1.4+18

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  firebase_storage: ^4.0.1
  firebase_database: ^4.1.1
  modal_progress_hud: ^0.1.3
  image_picker: ^0.6.3+4
  http: ^0.12.0+4
  flutter_datetime_picker: ^1.3.4
  intl: ^0.16.1
  material_design_icons_flutter: 3.4.4995
  calendar_strip: ^1.0.0
  sqflite: ^1.2.2+1
  path_provider: ^1.6.5
  provider: ^4.0.4
  currency_textfield: ^1.0.3
  custom_navigator: ^0.3.0
  rich_alert: ^0.1.32
  google_fonts: ^1.1.0
  floating_search_bar: ^0.3.0
  url_launcher: ^5.7.2
  geolocator: ^6.1.1
  geocoder: ^0.2.1
  webview_flutter: ^1.0.5
  rflutter_alert: ^1.1.0
  firebase_messaging: ^7.0.3
  flutter_launcher_icons: ^0.7.5
  keyboard_actions: ^3.3.1+1
  flutter_swipe_action_cell: ^1.3.4
  geocoding: ^1.0.5
  sortedmap: ^0.4.2

dev_dependencies:
  flutter_test:
   sdk: flutter
  change_app_package_name: ^0.1.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.png"

flutter:
  uses-material-design: true

  fonts:
  - family: CustomIcons
    fonts:
      - asset: lib/fonts/CustomIcons.ttf

  assets:
    - images/