import 'dart:convert';

class Match {
  String awayShirtColor, homeShirtColor;
  final String competitionName,
      date,
      homeTeamName,
      awayTeamName,
      round,
      startTimestamp,
      venue,
      stage,
      stats,
      homeLineup,
      awayLineup;
  final int id,
      awayGoals,
      homeGoals,
      awayPenalties,
      homePenalties,
      competitionId,
      currentState,
      minute,
      nextState,
      lastPolled,
      homeTeamId,
      awayTeamId;

  Match(
      {this.awayShirtColor = '#FFFFFF',
      this.homeShirtColor  = '#FFFFFF',
      this.competitionName,
      this.date,
      this.homeTeamName,
      this.awayTeamName,
      this.id,
      this.round,
      this.startTimestamp,
      this.venue,
      this.awayGoals,
      this.homeGoals,
      this.awayPenalties,
      this.homePenalties,
      this.competitionId,
      this.currentState,
      this.minute,
      this.nextState,
      this.lastPolled,
      this.stage,
      this.stats,
      this.homeLineup,
      this.awayLineup,
      this.homeTeamId,
      this.awayTeamId});

  factory Match.fromFirebaseDict(var match) => Match(
        id: match["id"],
        awayShirtColor: match["awayTeam"]["shirtUrl"],
        homeShirtColor: match["homeTeam"]["shirtUrl"],
        awayTeamId: match["awayTeam"]["dbid"],
        homeTeamId: match["homeTeam"]["dbid"],
        awayGoals: match["awayGoals"] ?? 0,
        homeGoals: match["homeGoals"] ?? 0,
        awayPenalties: match["awayPenalties"] ?? -1,
        homePenalties: match["homePenalties"] ?? -1,
        awayTeamName: match["awayTeam"]["name"],
        competitionId: match["competition"]["dbid"],
        competitionName: match["competition"]["name"],
        currentState: match["currentState"],
        date: match["date"],
        homeTeamName: match["homeTeam"]["name"],
        lastPolled: match["lastPolled"],
        minute: match["minute"],
        nextState: match["nextState"],
        round: match["round"] != null ? match["round"]["name"].toString() : "-",
        startTimestamp: match["start"],
        venue: match["venue"] != null ? match["venue"]["name"] : "-",
        stage: match["stage"] != null ? match["stage"]["name"] + " " + match["stage"]["type"] : "-",
        stats: match["stats"] != null ? json.encode(match["stats"]) : null,
        homeLineup: match["homePlayers"] != null ? json.encode(match["homePlayers"]) : null,
        awayLineup: match["awayPlayers"] != null ? json.encode(match["awayPlayers"]) : null,
      );

  factory Match.fromMap(Map<dynamic, dynamic> json) => Match(
      id: json['id'],
      awayShirtColor: json['awayShirtColor'],
      homeShirtColor: json['homeShirtColor'],
      competitionName: json['competitionName'],
      date: json['date'],
      homeTeamName: json['homeTeamName'],
      awayTeamName: json['awayTeamName'],
      round: json['round'],
      startTimestamp: json['startTimestamp'].toString(),
      venue: json['venue'],
      awayGoals: json['awayGoals'],
      homeGoals: json['homeGoals'],
      awayPenalties: json['awayPenalties'],
      homePenalties: json['homePenalties'],
      competitionId: json['competitionId'],
      currentState: json['currentState'],
      minute: json['minute'],
      nextState: json['nextState'],
      lastPolled: json['lastPolled'],
      stage: json['stage'],
      stats: json['stats'],
      homeLineup: json['homeLineup'],
      awayLineup: json['awayLineup'],
      awayTeamId: json['awayTeamId'],
      homeTeamId: json['homeTeamId']);

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'awayShirtColor': awayShirtColor,
      'homeShirtColor': homeShirtColor,
      'competitionName': competitionName,
      'date': date,
      'homeTeamName': homeTeamName,
      'awayTeamName': awayTeamName,
      'round': round,
      'venue': venue,
      'awayGoals': awayGoals,
      'homeGoals': homeGoals,
      'awayPenalties': awayPenalties,
      'homePenalties': homePenalties,
      'competitionId': competitionId,
      'currentState': currentState,
      'minute': minute,
      'nextState': nextState,
      'lastPolled': lastPolled,
      'startTimestamp': startTimestamp,
      'stage': stage,
      'stats': stats,
      'homeLineup': homeLineup,
      'awayLineup': awayLineup,
      'homeTeamId': homeTeamId,
      'awayTeamId': awayTeamId
    };
  }

  @override
  String toString() {
    return 'Match{id: $date/$homeTeamName, dbid: $id, awayTeam: $awayTeamName, homeGoals: $homeGoals, awayGoals: $awayGoals}';
  }
}
